### ISSUE TITLE
in configuration file outstreams is redundant

### ISSUE THREAD

**Issue by Joelgranados** [borevitzlab/timestreamlib#146]
We already have a list of outstreams in the pipeline list. We can suck these names from the outstream argument in pipeline component imagewrite.

**Comment by Joelgranados** [comment]
What I mean is that we don't need to have an outstreams section as "-cor" and "-seg" are already implicit in the pipeline component arguments for "imagewrite"
```
pipeline:
- name: undistort
  mess: '---Perform optical undistortion---'
- name: colorcarddetect
  mess: '---Perform color card detection---'
- name: colorcorrect
  mess: '---Perform color correction---'
- name: traydetect
  mess: '---Perform tray detection---'
- name: potdetect
  mess: '---Perform pot detection---'
- name: imagewrite
  mess: '---Writing Image---'
  outstream: -cor
- name: plantextract
  mess: '---Performing plant segmentation---'
- name: featureextract
  mess: '---Extracting features---'
  features: ["all"]
- name: imagewrite
  mess: '---Writing Image---'
  outstream: -seg
  addStats: ["leafcount1"]
  masked: False
- name: writefeatures                                                                                                                                                         
  mess: '---Writing Features---'

outstreams:
    - { name: -cor }
    - { name: -seg }

general:
  startDate: { year: 2014, month: 06, day: 25, hour: 9, minute: 0, second: 0}
  enddate: {}
  startHourRange: { hour: 0, minute: 0, second: 0}
  endHourRange: { hour: 23, minute: 59, second: 59}
  timeInterval: 900
  visualise: False
```
